Issue #712
danielhrisca/asammdf pull request #714
Opened 2022-05-31 18:26 UTC by david32

#712 

empty list was created because those channels weren't loaded.
Continue loop and perform action only to the group of channels that was loaded

+

Black formatting

2022-06-01 04:34 UTC, danielhrisca requested changes

2022-06-01 04:34 UTC, danielhrisca commented on asammdf/mdf.py
> +            if len(channels) == 0:
```python
if not channels:
    continue
```

is cleaner

2022-06-01 05:03 UTC, david32 commented on asammdf/mdf.py
> +            if len(channels) == 0:
Done. :)

2022-06-02 05:32 UTC, danielhrisca commented
Thank you!

2022-06-02 05:32 UTC, merged